# Practical 3

## Requirements

The `tidyverse` and `nnet` packages are required for this section and can be installed with:

`install.packages(c("tidyverse","nnet"))`

You will also need previous experience with probability to best benefit from the materials.

## Lecture

<iframe 
  src="https://docs.google.com/presentation/d/1_n8ycxON2l7g1Wo_OOEVX1oXYNI-KNxt/preview" 
  width="640" 
  height="480" 
  frameborder="0" 
  allow="autoplay">
</iframe>

<!--<iframe width="640" height="360" src="YOUTUBE EMBED LINK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
-->

## Lab

### Linear regression

For this part of the practical, you can download this [**script**](./exercises/exercises_module3/scripts/linear_regression.Rmd).

The solutions for this part are in this [**script**](./exercises/exercises_module3/results/linear_regression_answers.Rmd).

### Logistic regression

For this part of the practical, you can download this [**script**](./exercises/exercises_module3/scripts/logistic_regression.Rmd).

The solutions for this part are in this [**script**](./exercises/exercises_module3/results/logistic_regression_answers.Rmd).

### Statistical testing

For this part of the practical, you can download this [**script**](./exercises/exercises_module3/scripts/testing.Rmd).

The solutions for this part are in this [**script**](./exercises/exercises_module3/results/testing_answers.Rmd).

